Updated theme and added shortcut to quit terminal

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,24 +1,218 @@
 #!/bin/bash
+#!/usr/bin/env bash
 
-set -e 
-YELLOW='\033[1;33m'
-GREEN='\033[1;32m'
-NC='\033[0m'
+#=============================================================================
+# install.sh --- bootstrap script for SpaceVim
+# Copyright (c) 2016-2017 Shidong Wang & Contributors
+# Author: Shidong Wang < wsdjeg at 163.com >
+# URL: https://spacevim.org
+# License: GPLv3
+#=============================================================================
 
-mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/colors
+# Init option {{{
+Color_off='\033[0m'       # Text Reset
 
-#Install the pathogen plugin manager
-curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
+# terminal color template {{{
+# Regular Colors
+Black='\033[0;30m'        # Black
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Yellow='\033[0;33m'       # Yellow
+Blue='\033[0;34m'         # Blue
+Purple='\033[0;35m'       # Purple
+Cyan='\033[0;36m'         # Cyan
+White='\033[0;37m'        # White
 
-#Installing plugins
-git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
-git clone https://github.com/jistr/vim-nerdtree-tabs.git ~/.vim/bundle/vim-nerdtree-tabs
-git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim
+# Bold
+BBlack='\033[1;30m'       # Black
+BRed='\033[1;31m'         # Red
+BGreen='\033[1;32m'       # Green
+BYellow='\033[1;33m'      # Yellow
+BBlue='\033[1;34m'        # Blue
+BPurple='\033[1;35m'      # Purple
+BCyan='\033[1;36m'        # Cyan
+BWhite='\033[1;37m'       # White
 
-#Install the peaksea colour scheme
-wget -q --show-progress https://raw.githubusercontent.com/vim-scripts/peaksea/master/colors/peaksea.vim -P ~/.vim/colors
+# Underline
+UBlack='\033[4;30m'       # Black
+URed='\033[4;31m'         # Red
+UGreen='\033[4;32m'       # Green
+UYellow='\033[4;33m'      # Yellow
+UBlue='\033[4;34m'        # Blue
+UPurple='\033[4;35m'      # Purple
+UCyan='\033[4;36m'        # Cyan
+UWhite='\033[4;37m'       # White
 
-#Copy vimrc contents into ~/.vimrc
-cat vimrc > ~/.vimrc
+# Background
+On_Black='\033[40m'       # Black
+On_Red='\033[41m'         # Red
+On_Green='\033[42m'       # Green
+On_Yellow='\033[43m'      # Yellow
+On_Blue='\033[44m'        # Blue
+On_Purple='\033[45m'      # Purple
+On_Cyan='\033[46m'        # Cyan
+On_White='\033[47m'       # White
 
-echo -e "\n${GREEN}VIM-IDE has been successfully installed${NC}"
+# High Intensity
+IBlack='\033[0;90m'       # Black
+IRed='\033[0;91m'         # Red
+IGreen='\033[0;92m'       # Green
+IYellow='\033[0;93m'      # Yellow
+IBlue='\033[0;94m'        # Blue
+IPurple='\033[0;95m'      # Purple
+ICyan='\033[0;96m'        # Cyan
+IWhite='\033[0;97m'       # White
+
+# Bold High Intensity
+BIBlack='\033[1;90m'      # Black
+BIRed='\033[1;91m'        # Red
+BIGreen='\033[1;92m'      # Green
+BIYellow='\033[1;93m'     # Yellow
+BIBlue='\033[1;94m'       # Blue
+BIPurple='\033[1;95m'     # Purple
+BICyan='\033[1;96m'       # Cyan
+BIWhite='\033[1;97m'      # White
+
+# High Intensity backgrounds
+On_IBlack='\033[0;100m'   # Black
+On_IRed='\033[0;101m'     # Red
+On_IGreen='\033[0;102m'   # Green
+On_IYellow='\033[0;103m'  # Yellow
+On_IBlue='\033[0;104m'    # Blue
+On_IPurple='\033[0;105m'  # Purple
+On_ICyan='\033[0;106m'    # Cyan
+On_IWhite='\033[0;107m'   # White
+# }}}
+
+# version
+Version='1.3.0-dev'
+#System name
+System="$(uname -s)"
+
+# }}}
+
+# need_cmd {{{
+need_cmd () {
+    if ! hash "$1" &>/dev/null; then
+        error "Need '$1' (command not found)"
+        exit 1
+    fi
+}
+# }}}
+
+# success/info/error/warn {{{
+msg() {
+    printf '%b\n' "$1" >&2
+}
+
+success() {
+    msg "${Green}[✔]${Color_off} ${1}${2}"
+}
+
+info() {
+    msg "${Blue}[➭]${Color_off} ${1}${2}"
+}
+
+error() {
+    msg "${Red}[✘]${Color_off} ${1}${2}"
+    exit 1
+}
+
+warn () {
+    msg "${Yellow}[⚠]${Color_off} ${1}${2}"
+}
+# }}}
+
+# echo_with_color {{{
+echo_with_color () {
+    printf '%b\n' "$1$2$Color_off" >&2
+}
+# }}}
+
+install_pathogen()
+{
+	info "Installing pathogen"
+	mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/colors
+
+	if [ ! -f ~/.vim/autoload/pathogen.vim ]
+	then
+		curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
+	fi
+
+	success "Successfully installed pathogen"
+}
+
+install_plugins()
+{
+	info "Installing NERDTree"
+	
+	if [ ! -d ~/.vim/bundle/nerdtree ]
+	then
+		git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
+		success "Successfully installed NERDTree"
+	else
+		success "NERDTree already present"
+	fi
+
+	info "Installing NERDtreeTabs"
+
+	if [ ! -d ~/.vim/bundle/vim-nerdtree-tabs ]
+	then
+		git clone https://github.com/jistr/vim-nerdtree-tabs.git ~/.vim/bundle/vim-nerdtree-tabs
+		success "Successfully installed NERDTreeTabs"
+	else
+		success "NERDTreeTabs already present"
+	fi
+
+	info "Installing lightline"
+
+	if [ ! -d ~/.vim/bundle/lightline.vim ]
+	then
+		git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim
+		success "Successfully installed lightline"
+	else
+		success "Lightline already present"
+	fi
+}
+
+install_colourscheme()
+{
+	info "Installing the solarized colour scheme"
+
+	if [ ! -f ~/.vim/colors/solarized8_flat.vim ]
+	then
+		wget -q --show-progress	\
+		"https://raw.githubusercontent.com/lifepillar/vim-solarized8/master/colors/solarized8_flat.vim"    \
+		-P ~/.vim/colors/
+
+		success "Successfully installed the solarized colour scheme"
+	else
+		success "Solarized colour scheme already present"
+	fi
+
+}
+
+copy_vimrc()
+{
+	cat vimrc > ~/.vimrc
+}
+
+finished()
+{
+	success "Vim-IDE has been successfully installed"
+}
+
+main()
+{
+	install_pathogen
+	install_plugins
+	install_colourscheme
+	copy_vimrc
+	finished
+}
+
+main
+
+
+
+
